server:
  port: 8080

spring:
  application:
    name: order-management
  mvc:
    servlet:
      path: /order-management
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://78.47.116.96:3306/P1_Trainee
    username: trainee
    password: 966qiYSUK08f
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

beaconfire:
  authsome:
    base-url: https://api-v2.beaconfireinc.com
    tenant-id: t_2d2dbb07-b218-4ac7-9096-c86b604e7e04

app:
  config:
    access-key: "dummy_access_2e65d048-261e-4f61-b6a7-524d5d3e4c0d"
    secret-key: "dummy_secret_adaf69e7-7975-4c86-8c6c-774dc8dd09f4"
    account-mgmt-base-url: "https://tcs-api.beaconfireinc.com/account-mgmt/"
